INSERT INTO [dbo].[PessoaFisica_PFI]
           ([IdPfi]
           ,[Nome]
           ,[Profissao]
           ,[Sexo]
           ,[Telefone1]
           ,[Telefone2]
           ,[Indicacao]
           ,[Cargo]
           ,[Conjuge]
           ,[DataNascimento]
           ,[Email]
           ,[Foto]
           ,[DocumentoIdentificacaoSocial]
           ,[Rg]
           ,[IdEnd]
           ,[IdSit]
           ,[IdPju]
           ,[IdTme]
           ,[IdAte])
     VALUES
           (@IdPFisica
           ,@Nome
           ,@Profissao
           ,@Sexo
           ,@Telefone1
           ,@Telefone2
           ,@Indicacao
           ,@Cargo
           ,@Conjuge
           ,@DataNascimento
           ,@Email
           ,@Foto
           ,@DocumentoIdentificacaoSocial
           ,@Rg
           ,@IdEndereco
           ,@IdSituacaoCadastral
           ,@IdPessoaJuridica
           ,@IdTipoMembro
           ,@IdAtendente)